### ISSUE TITLE
Comics: Seitenhintergrund selbe Farbe wie Comichintergrund

### ISSUE THREAD

**Issue by Nachtfalter** [clonkspot/frontend#29]
Dann wäre der Comic optisch viel besser eingebunden. Die Schriftfarbe in den Archiven sollte dann aber auch entsprechend günstig erscheinen. Vielleicht eine kleine Tabelle mit Farben anlegen?

**Comment by lluchs** [comment]
Wenn das für dich ok ist würde ich einfach pro Comic zusätzlich Hintergrund- und Schriftfarbe angeben. Dann hast du immer volle Flexibilität. 

On March 5, 2015 3:39:43 PM CET, Nachtfalter <notifications@github.com> wrote:
>Dann wäre der Comic optisch viel besser eingebunden. Die Schriftfarbe
>in den Archiven sollte dann aber auch entsprechend günstig erscheinen.
>Vielleicht eine kleine Tabelle mit Farben anlegen?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/clonkspot/frontend/issues/29

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Nachtfalter** [comment]
Klingt gut!
